import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const DIST = "dist";
fs.mkdirSync(DIST, { recursive: true });

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${DIST}/main.js`,
});

function copyManifest() {
	fs.copyFileSync("manifest.json", path.join(DIST, "manifest.json"));
	// Phase 12.3 — ship the changelog alongside the plugin for the in-app modal.
	if (fs.existsSync("CHANGELOG.md")) {
		fs.copyFileSync("CHANGELOG.md", path.join(DIST, "CHANGELOG.md"));
	}
}

if (prod) {
	await context.rebuild();
	copyManifest();
	process.exit(0);
} else {
	copyManifest();
	await context.watch();
}
