/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DriveFolderSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// auth/GoogleAuth.ts
var crypto = __toESM(require("crypto"));
var http = __toESM(require("http"));
var import_url = require("url");
var { shell } = require("electron");
var CREDENTIALS_PATH = ".obsidian/drive-sync-credentials.json";
var REDIRECT_PORT = 42813;
var REDIRECT_URI = `http://localhost:${REDIRECT_PORT}`;
var TOKEN_URL = "https://oauth2.googleapis.com/token";
var AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
var SCOPE = "https://www.googleapis.com/auth/drive.readonly";
var GoogleAuth = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async isAuthorized() {
    const creds = await this.loadCredentials();
    return creds !== null;
  }
  async authorize() {
    const verifier = this.generateCodeVerifier();
    const challenge = this.generateCodeChallenge(verifier);
    const params = new URLSearchParams({
      client_id: this.settings.clientId,
      redirect_uri: REDIRECT_URI,
      response_type: "code",
      scope: SCOPE,
      code_challenge: challenge,
      code_challenge_method: "S256",
      access_type: "offline",
      prompt: "consent"
    });
    const authUrl = `${AUTH_URL}?${params}`;
    const codePromise = this.waitForAuthCode();
    await shell.openExternal(authUrl);
    const code = await codePromise;
    await this.exchangeCode(code, verifier);
  }
  async getValidAccessToken() {
    const creds = await this.loadCredentials();
    if (!creds) {
      throw new Error(
        "Not authenticated. Please connect to Google Drive in plugin settings."
      );
    }
    if (Date.now() < creds.expiry - 6e4) {
      return creds.access_token;
    }
    return this.refreshAccessToken(creds.refresh_token);
  }
  async disconnect() {
    const exists = await this.app.vault.adapter.exists(CREDENTIALS_PATH);
    if (exists) {
      await this.app.vault.adapter.remove(CREDENTIALS_PATH);
    }
  }
  async exchangeCode(code, verifier) {
    const resp = await fetch(TOKEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: this.settings.clientId,
        client_secret: this.settings.clientSecret,
        redirect_uri: REDIRECT_URI,
        grant_type: "authorization_code",
        code,
        code_verifier: verifier
      })
    });
    if (!resp.ok) {
      throw new Error(
        `Authorization failed: ${resp.status} ${await resp.text()}`
      );
    }
    const data = await resp.json();
    if (!data.refresh_token) {
      throw new Error(
        "No refresh token returned. Ensure prompt=consent and access_type=offline are set."
      );
    }
    await this.saveCredentials({
      refresh_token: data.refresh_token,
      access_token: data.access_token,
      expiry: Date.now() + data.expires_in * 1e3
    });
  }
  async refreshAccessToken(refreshToken) {
    const resp = await fetch(TOKEN_URL, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        client_id: this.settings.clientId,
        client_secret: this.settings.clientSecret,
        refresh_token: refreshToken,
        grant_type: "refresh_token"
      })
    });
    if (!resp.ok) {
      throw new Error(
        `Token refresh failed: ${resp.status} ${await resp.text()}`
      );
    }
    const data = await resp.json();
    const newCreds = {
      refresh_token: refreshToken,
      // Drive doesn't always return a new one
      access_token: data.access_token,
      expiry: Date.now() + data.expires_in * 1e3
    };
    await this.saveCredentials(newCreds);
    return newCreds.access_token;
  }
  waitForAuthCode() {
    return new Promise((resolve, reject) => {
      const server = http.createServer((req, res) => {
        var _a;
        try {
          const url = new import_url.URL((_a = req.url) != null ? _a : "/", `http://localhost:${REDIRECT_PORT}`);
          const code = url.searchParams.get("code");
          const error = url.searchParams.get("error");
          res.writeHead(200, { "Content-Type": "text/html" });
          res.end(
            "<h1>Authorization complete.</h1><p>You can close this tab and return to Obsidian.</p>"
          );
          server.close();
          if (code) {
            resolve(code);
          } else {
            reject(new Error(error != null ? error : "No authorization code received"));
          }
        } catch (e) {
          server.close();
          reject(e);
        }
      });
      server.listen(REDIRECT_PORT, "127.0.0.1", () => {
      });
      server.on("error", (err) => {
        reject(new Error(`Failed to start auth server: ${err.message}`));
      });
      const timeout = setTimeout(() => {
        server.close();
        reject(new Error("Authorization timed out after 5 minutes"));
      }, 5 * 60 * 1e3);
      server.on("close", () => clearTimeout(timeout));
    });
  }
  async saveCredentials(creds) {
    await this.app.vault.adapter.write(
      CREDENTIALS_PATH,
      JSON.stringify(creds, null, 2)
    );
  }
  async loadCredentials() {
    try {
      const exists = await this.app.vault.adapter.exists(CREDENTIALS_PATH);
      if (!exists)
        return null;
      const raw = await this.app.vault.adapter.read(CREDENTIALS_PATH);
      return JSON.parse(raw);
    } catch (e) {
      return null;
    }
  }
  generateCodeVerifier() {
    return crypto.randomBytes(32).toString("base64url");
  }
  generateCodeChallenge(verifier) {
    return crypto.createHash("sha256").update(verifier).digest("base64url");
  }
};

// sync/DriveSync.ts
var FILES_API = "https://www.googleapis.com/drive/v3/files";
var DriveSync = class {
  constructor(auth, downloader, settings, app) {
    this.auth = auth;
    this.downloader = downloader;
    this.settings = settings;
    this.app = app;
  }
  async sync() {
    const token = await this.auth.getValidAccessToken();
    const driveEntries = await this.collectFiles(
      this.settings.driveFolderId,
      "",
      token
    );
    const result = {
      downloaded: 0,
      skipped: 0,
      errors: 0,
      removed: 0
    };
    for (const entry of driveEntries) {
      try {
        const needsDownload = await this.shouldDownload(entry);
        if (needsDownload) {
          await this.downloader.download(
            entry.file,
            token,
            this.settings.vaultDestFolder,
            entry.relPath
          );
          result.downloaded++;
        } else {
          result.skipped++;
        }
      } catch (e) {
        console.error(
          `[DriveSync] Failed to sync "${entry.file.name}":`,
          e
        );
        result.errors++;
      }
    }
    if (this.settings.deletionBehavior !== "keep") {
      const driveManifest = new Set(
        driveEntries.map((e) => {
          const folder = e.relPath ? `${this.settings.vaultDestFolder}/${e.relPath}` : this.settings.vaultDestFolder;
          return `${folder}/${this.sanitizeFilename(e.file.name)}`;
        })
      );
      const removed = await this.processDeletions(
        this.settings.vaultDestFolder,
        driveManifest,
        token
      );
      result.removed = removed;
    }
    return result;
  }
  async collectFiles(folderId, relPath, token) {
    const [files, subfolders] = await Promise.all([
      this.listItems(
        token,
        `'${folderId}' in parents and mimeType='application/pdf' and trashed=false`,
        "files(id,name,modifiedTime,size)"
      ),
      this.listItems(
        token,
        `'${folderId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`,
        "files(id,name)"
      )
    ]);
    const entries = files.map((f) => ({ file: f, relPath }));
    for (const folder of subfolders) {
      const childRelPath = relPath ? `${relPath}/${folder.name}` : folder.name;
      const childEntries = await this.collectFiles(
        folder.id,
        childRelPath,
        token
      );
      entries.push(...childEntries);
    }
    return entries;
  }
  async listItems(token, query, fields) {
    var _a;
    const items = [];
    let pageToken;
    do {
      const params = new URLSearchParams({
        q: query,
        fields: `nextPageToken,${fields}`,
        pageSize: "1000"
      });
      if (pageToken)
        params.set("pageToken", pageToken);
      const resp = await fetch(`${FILES_API}?${params}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (!resp.ok) {
        throw new Error(
          `Drive files.list failed: ${resp.status} ${await resp.text()}`
        );
      }
      const data = await resp.json();
      items.push(...(_a = data.files) != null ? _a : []);
      pageToken = data.nextPageToken;
    } while (pageToken);
    return items;
  }
  async shouldDownload(entry) {
    const folder = entry.relPath ? `${this.settings.vaultDestFolder}/${entry.relPath}` : this.settings.vaultDestFolder;
    const localPath = `${folder}/${this.sanitizeFilename(entry.file.name)}`;
    const exists = await this.app.vault.adapter.exists(localPath);
    if (!exists)
      return true;
    const stat = await this.app.vault.adapter.stat(localPath);
    if (!stat)
      return true;
    const driveModified = new Date(entry.file.modifiedTime).getTime();
    return driveModified > stat.mtime;
  }
  async processDeletions(vaultFolder, driveManifest, _token) {
    let removed = 0;
    const folderExists = await this.app.vault.adapter.exists(vaultFolder);
    if (!folderExists)
      return 0;
    const allVaultFiles = this.app.vault.getFiles().filter(
      (f) => f.path.startsWith(vaultFolder + "/") || f.path === vaultFolder
    );
    for (const vaultFile of allVaultFiles) {
      if (!driveManifest.has(vaultFile.path)) {
        try {
          await this.removeFile(vaultFile);
          removed++;
        } catch (e) {
          console.error(
            `[DriveSync] Failed to remove "${vaultFile.path}":`,
            e
          );
        }
      }
    }
    return removed;
  }
  async removeFile(file) {
    if (this.settings.deletionBehavior === "delete") {
      await this.app.vault.trash(file, true);
    } else if (this.settings.deletionBehavior === "archive") {
      const relToRoot = file.path.slice(
        this.settings.vaultDestFolder.length
      );
      const archivePath = `${this.settings.archiveFolder}${relToRoot}`;
      const archiveDir = archivePath.substring(
        0,
        archivePath.lastIndexOf("/")
      );
      await this.ensureArchiveFolder(archiveDir);
      await this.app.fileManager.renameFile(file, archivePath);
    }
  }
  async ensureArchiveFolder(folderPath) {
    const segments = folderPath.split("/").filter(Boolean);
    let current = "";
    for (const seg of segments) {
      current = current ? `${current}/${seg}` : seg;
      const exists = await this.app.vault.adapter.exists(current);
      if (!exists) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  sanitizeFilename(name) {
    return name.replace(/[/\\:*?"<>|]/g, "_");
  }
};

// sync/DownloadManager.ts
var DownloadManager = class {
  constructor(app) {
    this.app = app;
  }
  async download(file, token, destFolder, relPath) {
    const folderPath = relPath ? `${destFolder}/${relPath}` : destFolder;
    await this.ensureFolder(folderPath);
    const safeName = this.sanitizeFilename(file.name);
    const localPath = `${folderPath}/${safeName}`;
    const resp = await fetch(
      `https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    if (!resp.ok) {
      throw new Error(
        `Download failed for "${file.name}": HTTP ${resp.status}`
      );
    }
    const buffer = await resp.arrayBuffer();
    const exists = await this.app.vault.adapter.exists(localPath);
    if (exists) {
      await this.app.vault.adapter.writeBinary(localPath, buffer);
    } else {
      await this.app.vault.createBinary(localPath, buffer);
    }
  }
  async ensureFolder(folderPath) {
    const segments = folderPath.split("/").filter(Boolean);
    let current = "";
    for (const seg of segments) {
      current = current ? `${current}/${seg}` : seg;
      const exists = await this.app.vault.adapter.exists(current);
      if (!exists) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  sanitizeFilename(name) {
    return name.replace(/[/\\:*?"<>|]/g, "_");
  }
};

// sync/Scheduler.ts
var Scheduler = class {
  constructor() {
    this.intervalId = null;
  }
  start(intervalMinutes, callback) {
    this.stop();
    if (intervalMinutes <= 0)
      return;
    const ms = intervalMinutes * 60 * 1e3;
    this.intervalId = window.setInterval(async () => {
      try {
        await callback();
      } catch (e) {
        console.error("[DriveSync] Scheduled sync error:", e);
      }
    }, ms);
  }
  stop() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  restart(intervalMinutes, callback) {
    this.stop();
    this.start(intervalMinutes, callback);
  }
};

// settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var DriveSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Drive Folder Sync" });
    containerEl.createEl("h3", { text: "Google Cloud credentials" });
    new import_obsidian.Setting(containerEl).setName("Client ID").setDesc(
      "OAuth2 Client ID from your Google Cloud Console project (Desktop app type)"
    ).addText(
      (text) => text.setPlaceholder("paste client_id here").setValue(this.plugin.settings.clientId).onChange(async (val) => {
        this.plugin.settings.clientId = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Client Secret").setDesc("OAuth2 Client Secret from the same Google Cloud Console project").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("paste client_secret here").setValue(this.plugin.settings.clientSecret).onChange(async (val) => {
        this.plugin.settings.clientSecret = val;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Google account" });
    new import_obsidian.Setting(containerEl).setName("Connect Google Drive").setDesc(
      "Authorize access to Google Drive. You only need to do this once. Your browser will open for Google's consent screen."
    ).addButton(
      (btn) => btn.setButtonText("Connect").onClick(async () => {
        if (!this.plugin.settings.clientId || !this.plugin.settings.clientSecret) {
          new import_obsidian.Notice(
            "Please enter your Client ID and Client Secret first."
          );
          return;
        }
        try {
          btn.setButtonText("Connecting\u2026").setDisabled(true);
          await this.plugin.auth.authorize();
          new import_obsidian.Notice("Google Drive connected successfully!");
        } catch (e) {
          new import_obsidian.Notice(`Authorization failed: ${e.message}`);
        } finally {
          btn.setButtonText("Connect").setDisabled(false);
        }
      })
    ).addButton(
      (btn) => btn.setButtonText("Disconnect").setWarning().onClick(async () => {
        await this.plugin.auth.disconnect();
        new import_obsidian.Notice("Google Drive disconnected.");
      })
    );
    containerEl.createEl("h3", { text: "Sync settings" });
    new import_obsidian.Setting(containerEl).setName("Drive folder ID").setDesc(
      "The ID at the end of the Drive folder URL: drive.google.com/drive/folders/FOLDER_ID_HERE"
    ).addText(
      (text) => text.setPlaceholder("1aBcDeFgHiJkLmNo\u2026").setValue(this.plugin.settings.driveFolderId).onChange(async (val) => {
        this.plugin.settings.driveFolderId = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Vault destination folder").setDesc(
      "Folder inside your vault where synced files will appear. Created automatically if missing."
    ).addText(
      (text) => text.setPlaceholder("Drive Sync").setValue(this.plugin.settings.vaultDestFolder).onChange(async (val) => {
        this.plugin.settings.vaultDestFolder = val.trim() || "Drive Sync";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to automatically sync. Set to 0 to disable automatic sync.").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.syncIntervalMinutes = num;
          await this.plugin.saveSettings();
          this.plugin.scheduler.restart(
            num,
            () => this.plugin.runSync()
          );
        }
      })
    );
    containerEl.createEl("h3", { text: "Deletion behavior" });
    let archiveSetting;
    new import_obsidian.Setting(containerEl).setName("When a file is removed from Drive").setDesc("What to do with vault files that no longer exist in the Drive folder.").addDropdown((drop) => {
      drop.addOption("keep", "Keep in vault").addOption("delete", "Move to system trash").addOption("archive", "Move to archive folder").setValue(this.plugin.settings.deletionBehavior).onChange(async (val) => {
        this.plugin.settings.deletionBehavior = val;
        await this.plugin.saveSettings();
        archiveSetting.settingEl.toggle(val === "archive");
      });
    });
    archiveSetting = new import_obsidian.Setting(containerEl).setName("Archive folder").setDesc(
      "Vault folder to move removed files into. Subfolder structure is preserved."
    ).addText(
      (text) => text.setPlaceholder("Drive Sync Archive").setValue(this.plugin.settings.archiveFolder).onChange(async (val) => {
        this.plugin.settings.archiveFolder = val.trim() || "Drive Sync Archive";
        await this.plugin.saveSettings();
      })
    );
    archiveSetting.settingEl.toggle(
      this.plugin.settings.deletionBehavior === "archive"
    );
    containerEl.createEl("h3", { text: "Manual sync" });
    new import_obsidian.Setting(containerEl).setName("Sync now").setDesc("Trigger a one-off sync immediately.").addButton(
      (btn) => btn.setButtonText("Sync now").onClick(async () => {
        try {
          btn.setButtonText("Syncing\u2026").setDisabled(true);
          const result = await this.plugin.runSync();
          new import_obsidian.Notice(
            `Sync complete \u2014 ${result.downloaded} downloaded, ${result.skipped} up to date` + (result.removed > 0 ? `, ${result.removed} removed` : "") + (result.errors > 0 ? `, ${result.errors} errors` : "")
          );
        } catch (e) {
          new import_obsidian.Notice(`Sync failed: ${e.message}`);
        } finally {
          btn.setButtonText("Sync now").setDisabled(false);
        }
      })
    );
  }
};

// types.ts
var DEFAULT_SETTINGS = {
  clientId: "",
  clientSecret: "",
  driveFolderId: "",
  vaultDestFolder: "Drive Sync",
  syncIntervalMinutes: 30,
  deletionBehavior: "keep",
  archiveFolder: "Drive Sync Archive"
};

// main.ts
var DriveFolderSyncPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.syncing = false;
  }
  async onload() {
    await this.loadSettings();
    const downloader = new DownloadManager(this.app);
    this.auth = new GoogleAuth(this.app, this.settings);
    this.driveSync = new DriveSync(
      this.auth,
      downloader,
      this.settings,
      this.app
    );
    this.scheduler = new Scheduler();
    this.addRibbonIcon("refresh-cw", "Sync Drive folder", async () => {
      if (this.syncing) {
        new import_obsidian2.Notice("Sync already in progress\u2026");
        return;
      }
      try {
        const result = await this.runSync();
        new import_obsidian2.Notice(
          `Drive sync complete \u2014 ${result.downloaded} downloaded, ${result.skipped} up to date` + (result.removed > 0 ? `, ${result.removed} removed` : "") + (result.errors > 0 ? `, ${result.errors} errors` : "")
        );
      } catch (e) {
        new import_obsidian2.Notice(`Drive sync failed: ${e.message}`);
      }
    });
    this.addSettingTab(new DriveSyncSettingTab(this.app, this));
    const isAuthorized = await this.auth.isAuthorized();
    if (isAuthorized) {
      this.scheduler.start(
        this.settings.syncIntervalMinutes,
        () => this.runSync()
      );
    }
  }
  onunload() {
    this.scheduler.stop();
  }
  async runSync() {
    if (this.syncing) {
      return { downloaded: 0, skipped: 0, errors: 0, removed: 0 };
    }
    this.syncing = true;
    try {
      return await this.driveSync.sync();
    } finally {
      this.syncing = false;
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.auth)
      this.auth.updateSettings(this.settings);
    if (this.driveSync) {
      const downloader = new DownloadManager(this.app);
      this.driveSync = new DriveSync(
        this.auth,
        downloader,
        this.settings,
        this.app
      );
    }
  }
};
