import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const DIST = "dist";
fs.mkdirSync(DIST, { recursive: true });
const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: "/* Generated by esbuild. */" },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: `${DIST}/main.js`
});

function copyReleaseFiles() {
  fs.copyFileSync("manifest.json", path.join(DIST, "manifest.json"));
  if (fs.existsSync("README.md")) fs.copyFileSync("README.md", path.join(DIST, "README.md"));
}

if (prod) {
  await context.rebuild();
  copyReleaseFiles();
  await context.dispose();
  process.exit(0);
}

copyReleaseFiles();
await context.watch();
